import Head from "next/head";
import Publications from "@/components/Settings/Publications";
import { useManagement } from "@/context/ManagementContext";
import { Author as AuthorContainer } from "@/components/Author";
import Drafts from "@/components/Settings/Drafts";
import Disabled from "@/components/Settings/Disabled";
import Comments from "@/components/Manager/Comments";
import { GetServerSideProps } from "next";
import { useMemo } from "react";


export default function Author() {
  const PublicationsMemo = useMemo(() => <Publications />, [])
  const DraftsMemo = useMemo(() => <Drafts />, [])
  const DisabledMemo = useMemo(() => <Disabled />, [])
  const AuthorssMemo = useMemo(() => <Comments/>, [])

    const { navigation } = useManagement()
    return (
      <>
        <Head>
            <title>Author | ARTechCMS</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <AuthorContainer>
        {
            navigation === "" ? PublicationsMemo : 
            navigation === "drafts" ? DraftsMemo : 
            navigation === "disabled" ? DisabledMemo : 
            navigation === "comments" ? AuthorssMemo : null
        }
        </AuthorContainer>
      </>
    )
  }

  export const getServerSideProps: GetServerSideProps = async ({req, res, params}) => {
  
    let hierarchy = "author" 
    if (hierarchy === "admin") {
      return {
        redirect: {
          destination: '/admin',
          permanent: true
        }
      }
    } else if (hierarchy !== "author"){
      return {
        redirect: {
          destination: '/',
          permanent: true
        }
      }
    }
  
    return {
      props: {
        
      }
    }
  }