import Head from 'next/head'
import { Flex, Text, Box, Stack, Button } from '@chakra-ui/react'
import { Input } from '@/components/Input/index'
import { useManagement } from '@/context/ManagementContext'
import { useRouter } from 'next/router'
import { Header } from '@/components/Header'
import { HeaderLink } from '@/components/Header/HeaderLink'
import { GetServerSideProps } from 'next'


export default function RegisterAuthor() {
  const {useHierarchy, hierarchy} = useManagement()
  const router = useRouter()
  function handleClick(){
    
    router.push(`${hierarchy}/`)
  }
  return (
    <>
      <Head>
        <title>Register Author | ARTechCMS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex direction="column" gap={{base: "0", md:"10"}}>
        <Header>
              <HeaderLink href='/admin'>Artigos</HeaderLink>
              <HeaderLink href='/create'>Criar</HeaderLink>
              <HeaderLink href='/register-author'>Adicionar autor</HeaderLink>
        </Header>
        <Flex alignSelf="center" as="main" justify="center" align="center" w="100vw" mb={{base: "5rem", sm: "4"}} py={{base: "0", sm: "4"}} px="4">
          <Flex as="form" gap={["8","12"]} direction="column" bg="gray.900" 
            px={["2rem","4rem"]}  py={{base: "2rem", sm:"5.25rem"}} w="100%" maxW="780px" borderRadius={8}>
            <Stack spacing="5">
              <Flex gap="4" direction={{base: "column", sm: "row"}}>
                <Input type='text' label='Nome'/>
                <Input type='email' label='E-mail'/>
              </Flex>
              <Flex gap="4" direction={{base: "column", sm: "row"}}>
                <Input type='password' label='Senha'/>
                <Input type='password' label='Confirmar Senha'/>
              </Flex>
            </Stack>
            <Button onClick={handleClick} size={['md','lg']} bg="purple.700" fontSize="xl" color="white"  _hover={{bgColor: 'purple.800'}}>
              Registrar
            </Button>
          </Flex>
        </Flex>
      </Flex>

    </>
  )
}
export const getServerSideProps: GetServerSideProps = async ({req, res, params}) => {
  
  let hierarchy = "admin" 
  if (hierarchy !== "admin") {
    return {
      redirect: {
        destination: '/author',
        permanent: true
      }
    }
  }

  return {
    props: {
      
    }
  }
}