import { Header } from "@/components/Header";
import { HeaderLink } from "@/components/Header/HeaderLink";
import Head from "next/head";

export default function Home() {
    return (
      <>
        <Head>
            <title>Admin | ARTechCMS</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header>
            <HeaderLink>
                Artigos
            </HeaderLink>
            <HeaderLink>
                Criar
            </HeaderLink>
            <HeaderLink>
                Adicionar autor
            </HeaderLink>
        </Header>
      </>
    )
  }