import Head from "next/head";
import React from 'react'
import { GetServerSideProps } from "next";
import { useQuery } from "react-query";
import { Stack, Icon, Flex, Text, Heading } from "@chakra-ui/react";
import { Main } from "../../components/Main";
import { RiArrowLeftSLine } from 'react-icons/ri'
import { useManagement } from "../../context/ManagementContext";
import Link from "next/link";


type Comments = {
  id: string;
  text: string;
  created_at: string;
  user_name: string;
}

export interface ArticleComments {
  comments: Comments[],
  article: {
      slug: string;
      title: string;
      category: string;
  }
}


export default function Comments() {

  const { data, isLoading, error } = useQuery('articles', async () => {
    const commentsResponse = await fetch("http://localhost:3000/api/comments")
    const [comments] = await commentsResponse.json()

    return {
      comments
    }

  })
  const { hierarchy } = useManagement()
  console.log(data?.comments);

    return (
      <>
        <Head>
            <title>Admin | ARTechCMS</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Main aside={false}>
            <Stack gap="10">
                <Link href={`/${hierarchy}`} style={{alignSelf:"flex-start"}}>
                    <Flex align="center" w="fit-content" transition="all" transitionDuration=".15s"
                    borderBottom={"1px"} borderColor='transparent' _hover={{ borderColor:'purple.700'}}>
                        <Icon as={RiArrowLeftSLine} color="purple.700" fontSize='3xl'/>
                        <Text as="span" fontWeight="bold">
                            VOLTAR
                        </Text>
                    </Flex>
                </Link>
                <Heading as='h1' fontWeight="black" >
                    Titulo do artigo sobre o Front-End e suas tecnologias
                    <Text as="strong" color="purple.300">!</Text> 
                </Heading>
                <Stack>
                    <Heading as='h1' fontFamily="Ubuntu" fontWeight="bold" fontSize="2xl">
                        Comentários 
                    </Heading>
                    <Stack borderRadius="4" bg="gray.800">
                        <Flex>
                            asd
                        </Flex>
                    </Stack>
                </Stack>
            </Stack>
        </Main>
      </>
    )
}

